### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by BasToTheMax** [AL1L/MCHPRS-Pterodactyl#1]
What will this repo be?

**Comment by AL1L** [comment]
I am going to put the Pterodactyl egg for MCHPRS here, forgot to push it before formatting my computer so I'll have to dig into the backups.

**Comment by BasToTheMax** [comment]
what is MCHPRS?

**Comment by AL1L** [comment]
Google works, https://github.com/MCHPR/MCHPRS

**Comment by BasToTheMax** [comment]
Ah okay. Thanks for your response
